title: Arya Chavoshi
description: Graduate Research Assistant <br> Department of Civil, Architectural, and Environmental Engineering, UT Austin
author: Arya Chavoshi
author_email: arya.chavoshi@utexas.edu
google_analytics: UA-52448613-2
theme: jekyll-theme-cayman
